//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Threading;
using System.Threading.Tasks;
using ClickUp.Api.Client.Models; // Assuming models will be in this namespace

namespace ClickUp.Api.Client.Abstractions
{
    /// <summary>
    /// Interface for ClickUp Authorization Service.
    /// Provides methods for OAuth 2.0 authentication and retrieving authorized user and team information.
    /// </summary>
    public interface IAuthorizationService
    {
        /// <summary>
        /// Get an OAuth 2.0 access token.
        /// </summary>
        /// <param name="clientId">The Client ID of your OAuth App.</param>
        /// <param name="clientSecret">The Client Secret of your OAuth App.</param>
        /// <param name="code">The code returned from the authorization redirect.</param>
        /// <param name="cancellationToken">An optional token to cancel the operation.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the access token response.</returns>
        /// <remarks>
        /// Corresponds to the ClickUp API operation <c>GetAccessToken</c> (<c>POST /v2/oauth/token</c>).
        /// </remarks>
        Task<GetAccessTokenResponse> GetAccessTokenAsync(string clientId, string clientSecret, string code, CancellationToken cancellationToken = default);

        /// <summary>
        /// View the details of the authenticated user's ClickUp account.
        /// </summary>
        /// <param name="cancellationToken">An optional token to cancel the operation.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the authorized user's details.</returns>
        /// <remarks>
        /// Corresponds to the ClickUp API operation <c>GetAuthorizedUser</c> (<c>GET /v2/user</c>).
        /// </remarks>
        Task<GetAuthorizedUserResponse> GetAuthorizedUserAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// View the Workspaces available to the authenticated user.
        /// </summary>
        /// <param name="cancellationToken">An optional token to cancel the operation.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the list of authorized teams (Workspaces).</returns>
        /// <remarks>
        /// Corresponds to the ClickUp API operation <c>GetAuthorizedTeams</c> (<c>GET /v2/team</c>).
        /// </remarks>
        Task<GetAuthorizedTeamsResponse> GetAuthorizedTeamsAsync(CancellationToken cancellationToken = default);
    }
}
