//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using ClickUp.Api.Client.Models.Entities; // For User and Workspace DTOs
using ClickUp.Api.Client.Models.ResponseModels.Authorization;

// Corrected namespace
namespace ClickUp.Api.Client.Abstractions.Services
{
    /// <summary>
    /// Interface for ClickUp Authorization Service.
    /// Provides methods for OAuth 2.0 authentication and retrieving authorized user and team information.
    /// </summary>
    public interface IAuthorizationService
    {
        /// <summary>
        /// Exchanges an authorization code for an access token.
        /// </summary>
        /// <param name="clientId">OAuth app client ID.</param>
        /// <param name="clientSecret">OAuth app client secret.</param>
        /// <param name="code">Authorization code received from redirect.</param>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the <see cref="AccessTokenResponse"/>.</returns>
        Task<AccessTokenResponse> GetAccessTokenAsync(
            string clientId,
            string clientSecret,
            string code,
            CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves the details of the authenticated user.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains the authorized <see cref="User"/>'s details.</returns>
        Task<User> GetAuthorizedUserAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves the Workspaces (Teams) available to the authenticated user.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token.</param>
        /// <returns>A task that represents the asynchronous operation. The task result contains a list of authorized <see cref="Workspace"/> objects.</returns>
        Task<IEnumerable<Workspace>> GetAuthorizedWorkspacesAsync(CancellationToken cancellationToken = default);
    }
}
